Update mount.h for susfs 1.5.3 support
error: no member named 'android_kabi_reservedx' in 'struct yyyyyyyy'

 Because normally the memeber u64 android_kabi_reservedx; doesn't exist in all structs with all kernel version below 4.19, and sometimes it is not guaranteed existed with kernel version >= 4.19 and <= 5.4, and even with GKI kernel, like some of the custom kernels has all of them disabled. So at this point if the susfs patches didn't have them patched for you, then what you need to do is to manually append the member to the end of the corresponding struct definition, it should be u64 android_kabi_reservedx; with the last x starting from 1, like u64 android_kabi_reserved1;, u64 android_kabi_reserved2; and so on. You may also refer to patch from other branches like kernel-4.14, kernel-4.9 of this repo for extra diff of the missing kabi members.